#!/bin/bash
#
# This file is part of Udctl.
# 
# Udctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# Udctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
# 
# You should have received a copy of the GNU General Public License along with
# Udctl. If not, see <https://www.gnu.org/licenses/>.


PREFIX="${0%/*}"
ACTION="$1" ; shift

case "${ACTION}" in
    'help')
	case "$1" in
	    'help')
		cat <<EOF
udctl help <command>

Print help about a given command.
EOF
		exit 0
		;;
	    'update-home')
		exec "${PREFIX}/udctl-update-home" --help
		;;
	    '')
		cat <<EOF
udctl <command> [ <args...> ]

Help user to manage its data and perform housekeeping in a semi automatic
fashion.

Commands:

  help                        Print detailed help about a command.

  update-home                 Keep the home directory synced with the /etc/skel
                              directory.
EOF
		exit 0
		;;
	    *)
		exit 1
		;;
	esac
	;;
    'update-home')
	exec "${PREFIX}/udctl-update-home" "$@"
	;;
    *)
	exit 1
	;;
esac
