#!/bin/bash

set -e
set -x

mkdir 'skel'
echo 'v0' > 'skel/f0'
mkdir 'skel/d0'
echo 'v0' > 'skel/d0/f1'
ln -s 'd0/f1' 'skel/l0'

cp -R 'skel' 'snapshot'
cp -R 'skel' 'home'

rm 'skel/f0'
rm -rf 'skel/d0'
rm 'skel/l0'

rm 'home/f0'
rm -rf 'home/d0'
rm 'home/l0'

udctl update-home --skel='skel' --home='home' --snapshot='snapshot' \
      --mode=diff > 'out'

test ! -s 'out'

cp -R 'skel' 'result'

diff -Naur --no-dereference 'home' 'result'
