#!/bin/bash

set -e
set -x

mkdir 'skel'
echo 'v0' > 'skel/f0'
mkdir 'skel/d0'
echo 'v0' > 'skel/d0/f1'
ln -s 'd0/f1' 'skel/l0'

cp -R 'skel' 'snapshot'
cp -R 'skel' 'home'

rm -rf 'skel/d0'
echo 'v0' > 'skel/d0'

rm -rf 'home/d0'
ln -s 'f0' 'home/d0'

cp -R 'home' 'result'

udctl update-home --skel='skel' --home='home' --snapshot='snapshot' \
      --mode=diff > 'out'

cat 'out' >&2

(
    read line ; echo "$line" | grep -q "'home/d0'.*modified"
) < 'out'

diff -Naur --no-dereference 'home' 'result'
