#!/bin/bash

set -e
set -x

mkdir 'skel'
echo 'v0' > 'skel/f0'
mkdir 'skel/d0'
echo 'v0' > 'skel/d0/f1'
ln -s 'd0/f1' 'skel/l0'

cp -R 'skel' 'home'

echo 'v1' > 'skel/f0'
rm 'skel/l0'
ln -s 'f0' 'skel/l0'

cp -R 'home' 'result'

udctl update-home --skel='skel' --home='home' --mode=forward > 'out'

cat 'out' >&2

(
    read line ; echo "$line" | grep -q "'home/f0'.*modified"
    read line ; echo "$line" | grep -q "'home/l0'.*modified"
) < 'out'

diff -Naur --no-dereference 'home' 'result'
